---
- name: Build Heat stack
  hosts: localhost
  gather_facts: false
  vars:
    heat_environment_file: "heat_params.yaml"

  tasks:
    - name: Build a Heat stack for the NGINX VM
      register: heat_stack
      openstack.cloud.stack:
        name: "{{ stack_name }}"
        state: present
        template: "servers_group.yaml"
        environment:
          - "{{ heat_environment_file }}"

    - name: Debug the Heat stack outputs
      ansible.builtin.debug:
        var: heat_stack

    - name: Wait for the VM to become accessible
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 22
        state: started
        timeout: 300
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"

    - name: Add host to the dynamic inventory
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: "os_instances_group"
        ansible_ssh_user: "{{ vm_user_account }}"
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
