---
- hosts: os_instances_group
  gather_facts: true
  become: true

  tasks:
    - name: Update the repository cache and install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
        update_cache: yes

    - name: Ensure nginx is started and enabled to start at boot
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes


    - name: Copy index.html to nginx root directory
      block:
        - name: Create nginx root directory
          ansible.builtin.file:
            path: /srv/www/html
            state: directory
            owner: root
            group: root
            mode: '0755'
        - name: Copy index.html
          ansible.builtin.copy:
            src: "{{ index_html_path }}"
            dest: /srv/www/html/index.html
            owner: root
            group: root
            mode: '0644'
        - name: Update nginx.conf
          ansible.builtin.lineinfile:
            path: /etc/nginx/nginx.conf
            regexp: '^(\s*)root(\s+)(.*;)$'
            backrefs: yes
            line: '\1root\2/srv/www/html;'
            state: present
            backup: yes
            mode: '0644'
        - name: Restart nginx
          ansible.builtin.service:
            name: nginx
            state: "reloaded"

